export const portfolioSeed = {
  snapshotLabel: "seed · tradingview-inspired portfolio",
  quotesUpdatedAt: "2026-06-15 09:18",
  alertsCheckedAt: "2026-06-15 09:20",
  mailStatus: "mock provider · idle",
  holdings: [
    {
      account: "schwab",
      broker: "嘉信",
      market: "US",
      marketLabel: "美股",
      assetClass: "ETF",
      symbol: "BOXX",
      name: "Alpha Architect 1-3 Month Box ETF",
      quantity: 22,
      avgCost: 115.5,
      currentPrice: 116.18,
      currency: "USD",
      priority: 1,
      alertEnabled: true,
      alertState: "price_below 115.00",
      alertTone: "amber",
    },
    {
      account: "schwab",
      broker: "嘉信",
      market: "US",
      marketLabel: "美股",
      assetClass: "ETF",
      symbol: "QQQI",
      name: "NEOS NASDAQ-100 High Income ETF",
      quantity: 3,
      avgCost: 49.7833,
      currentPrice: 50.92,
      currency: "USD",
      priority: 2,
      alertEnabled: true,
      alertState: "ma250_cross_up",
      alertTone: "green",
    },
    {
      account: "schwab",
      broker: "嘉信",
      market: "US",
      marketLabel: "美股",
      assetClass: "ETF",
      symbol: "SOXS",
      name: "Direxion Daily Semiconductor Bear 3X Shares",
      quantity: 1,
      avgCost: 14.35,
      currentPrice: 12.88,
      currency: "USD",
      priority: 3,
      alertEnabled: true,
      alertState: "bollinger_lower_break",
      alertTone: "red",
    },
    {
      account: "yinhe",
      broker: "银河证券",
      market: "CN",
      marketLabel: "A股",
      assetClass: "ETF",
      symbol: "159915.SZ",
      name: "创业板 ETF",
      quantity: 1000,
      avgCost: 1.0,
      currentPrice: 1.12,
      currency: "CNY",
      priority: 4,
      alertEnabled: false,
      alertState: "未启用",
      alertTone: "blue",
    },
    {
      account: "yinhe",
      broker: "银河证券",
      market: "CN",
      marketLabel: "A股",
      assetClass: "ETF",
      symbol: "512100.SH",
      name: "中证 1000 ETF",
      quantity: 1000,
      avgCost: 1.0,
      currentPrice: 0.98,
      currency: "CNY",
      priority: 5,
      alertEnabled: false,
      alertState: "未启用",
      alertTone: "blue",
    },
    {
      account: "yinhe",
      broker: "银河证券",
      market: "CN",
      marketLabel: "A股",
      assetClass: "ETF",
      symbol: "161716.SZ",
      name: "招商双债 ETF",
      quantity: 1000,
      avgCost: 1.0,
      currentPrice: 1.05,
      currency: "CNY",
      priority: 6,
      alertEnabled: false,
      alertState: "未启用",
      alertTone: "blue",
    },
  ],
  cashBalances: [
    {
      account: "ibkr",
      broker: "盈透",
      market: "CASH",
      marketLabel: "现金",
      currency: "CNY",
      cash: 50000,
    },
  ],
};
